console.log(Boolean("true"));
console.log(Boolean("TRUTH"));
console.log(Boolean(4 == "4"));
console.log(Boolean(" "));
console.log(Boolean(0));
console.log(Boolean(1));
console.log(Boolean('banana' <= 'apple'));
console.log(Boolean('apple' <= 'banana'));
let banana = true;
console.log(Boolean(banana === 'banana'));
console.log((3 + 4 === 7));